import React, { useState, useEffect } from 'react';
import { 
  View, ScrollView, Modal, TextInput, Share, Alert, 
  StyleSheet, TouchableOpacity, Text, Platform, SafeAreaView 
} from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft, Settings, Heart, Activity, Smartphone } from 'lucide-react-native';


import { 
  ClinicalBenchmark, EcosystemItem, EditorialHeader, 
  HealthStatsCard, SignOutButton 
} from '@/components/ui/ProfileComponents';
import { HealthConnection, healthService } from '@/service/healthService';

export default function ProfileScreen() {
  const router = useRouter();
  const [modalVisible, setModalVisible] = useState(false);
  const [glucoseTarget, setGlucoseTarget] = useState('70-140');
  const [connections, setConnections] = useState<HealthConnection[]>([]);

  // Cargar datos al montar la pantalla
  useEffect(() => {
    fetchHealthData();
  }, []);

  const fetchHealthData = async () => {
    const data = await healthService.getConnections();
    setConnections(data);
  };

  const handleToggleHealth = async (id: any) => {
    const success = await healthService.toggleConnection(id);
    if (success) {
      await fetchHealthData(); // Refrescar UI
    } else {
      Alert.alert("Error", "Could not update connection status.");
    }
  };

  const onShare = async () => {
    try {
      await Share.share({
        message: `📊 Health Report\nTarget Range: ${glucoseTarget} mg/dL\nStability: 82%.\nGenerated by Equilibrium 🌿`,
      });
    } catch (e) { console.error(e); }
  };

  return (
    <SafeAreaView style={styles.mainContainer}>
      {/* Navegación Superior */}
      <View style={styles.navBar}>
        <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
          <ArrowLeft color="#c4ebe0" size={24} />
        </TouchableOpacity>
        <Text style={styles.navTitle}>Profile</Text>
        <TouchableOpacity style={styles.iconBtn}>
          <Settings color="#c4ebe0" size={24} />
        </TouchableOpacity>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        <EditorialHeader 
          name="Elena Rodriguez" 
          condition="Type 1 Diabetes" 
          age={32} 
          imageUri="https://i.pravatar.cc/300?img=45" 
        />

        <View style={styles.actionRow}>
          <TouchableOpacity style={styles.primaryBtn} onPress={() => setModalVisible(true)}>
            <Text style={styles.btnText}>Edit Goals</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.secondaryBtn} onPress={onShare}>
            <Text style={styles.btnTextSecondary}>Share Report</Text>
          </TouchableOpacity>
        </View>

        <HealthStatsCard 
          label="Rolling 14-Day Average" 
          value="108" unit="mg/dL" trend="-4%" progress={82} 
        />

        <Text style={styles.sectionTitle}>Benchmarks</Text>
        <ClinicalBenchmark label="TARGET RANGE" value={glucoseTarget} unit="mg/dL" borderColor="#006782" />

        <Text style={[styles.sectionTitle, { marginTop: 24 }]}>Health Ecosystem</Text>
        <View style={styles.ecosystemContainer}>
          {connections.map((item) => (
            <EcosystemItem 
              key={item.id}
              name={item.name} 
              desc={item.connected ? "Data Active" : "Click to sync"} 
              connected={item.connected} 
              icon={
                item.id === 'apple' ? <Heart color="#ba1a1a" size={20} /> :
                item.id === 'google' ? <Activity color="#86d0ef" size={20} /> :
                <Smartphone color="#a4f4b7" size={20} />
              }
              onPress={() => handleToggleHealth(item.id)}
            />
          ))}
        </View>

        <SignOutButton onPress={() => router.replace('/')} />
      </ScrollView>

      {/* MODAL FUNCIONAL */}
      <Modal animationType="slide" transparent visible={modalVisible}>
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <Text style={styles.modalTitle}>Update Parameters</Text>
            <Text style={styles.label}>Glucose Range (mg/dL)</Text>
            <TextInput 
              style={styles.input} 
              value={glucoseTarget} 
              onChangeText={setGlucoseTarget}
              keyboardType="default"
              placeholderTextColor="#3f484c"
            />
            <TouchableOpacity style={styles.saveBtn} onPress={() => setModalVisible(false)}>
              <Text style={styles.saveBtnText}>Confirm Changes</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: '#171d1e' },
  navBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  navTitle: { color: '#c4ebe0', fontSize: 16, fontWeight: '700' },
  iconBtn: { padding: 8 },
  scrollContent: { paddingHorizontal: 24, paddingBottom: 40 },
  actionRow: { flexDirection: 'row', gap: 12, justifyContent: 'center', marginBottom: 30 },
  primaryBtn: { backgroundColor: '#004e63', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 100 },
  secondaryBtn: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 100 },
  btnText: { color: '#fff', fontWeight: '700' },
  btnTextSecondary: { color: '#c4ebe0', fontWeight: '700' },
  sectionTitle: { color: '#f5fafb', fontSize: 18, fontWeight: '800', marginBottom: 16 },
  ecosystemContainer: { backgroundColor: '#1d2426', borderRadius: 24, overflow: 'hidden' },
  // Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', padding: 24 },
  modalContent: { backgroundColor: '#1d2426', padding: 30, borderRadius: 32 },
  modalTitle: { color: '#c4ebe0', fontSize: 22, fontWeight: '800', marginBottom: 20 },
  label: { color: '#6f787d', fontSize: 12, fontWeight: '700', marginBottom: 8 },
  input: { backgroundColor: '#171d1e', color: '#fff', padding: 15, borderRadius: 16, marginBottom: 20 },
  saveBtn: { backgroundColor: '#006782', padding: 18, borderRadius: 100, alignItems: 'center' },
  saveBtnText: { color: '#fff', fontWeight: '800' }
});